# baseURL
@baseURL = http://localhost:4000

### Find All Users
GET {{ baseURL }}/users

### Modify User By Id
PUT {{ baseURL }}/users/1
Content-Type: application/json

{
  "email": "example@email.com",
  "password": "password"
}

### Delete User By Id
DELETE {{ baseURL }}/users/1
